plugins {
id 'com.android.application'
}

android {
namespace "ephemeralwp.safespace"
compileSdk 35

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "ephemeralwp.safespace"  
    minSdk 29
    targetSdk 37
    versionCode 57
    versionName "57.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}

}

dependencies {
}
